# Generated by Django 3.2.7 on 2021-09-22 03:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('level', models.PositiveIntegerField(editable=False)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent_departments', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employees.departments')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='full_name')),
                ('position', models.CharField(max_length=50, verbose_name='position')),
                ('employment_date', models.DateField(verbose_name='employment date')),
                ('size_of_salary', models.IntegerField(verbose_name='size of salary')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.departments', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'ordering': ['full_name'],
            },
        ),
    ]
